---
# Role used to customize IOSXRv using CVAC 
# Thanks to https://plajjan.github.io/2016-05-19-bootstrapping-virtual-XR.html
# and https://www.cisco.com/c/en/us/td/docs/ios_xr_sw/ios_xrv/install_config/b-xrv/b-xrv_chapter_011.html

- name: Create temporary "CVAC" directory
  ansible.builtin.file:
    path: /tmp/{{ item.value.name }}
    state: directory
    mode: '0755'

- name: Create XR template
  ansible.builtin.template:
    src: iosxr_config.txt.j2
    dest: /tmp/{{ item.value.name }}/iosxr_config.txt

- name: Create admin template
  ansible.builtin.template:
    src: iosxr_config_admin.txt.j2
    dest: /tmp/{{ item.value.name }}/iosxr_config_admin.txt

- name: Create "CVAC" file
  community.general.iso_create:
    src_files:
      - /tmp/{{ item.value.name }}/iosxr_config.txt
      - /tmp/{{ item.value.name }}/iosxr_config_admin.txt
    dest_iso: "{{ libvirt_pool_dir }}/{{ item.value.name }}-conf.iso"
    interchange_level: 2
    vol_ident: config-1

- name: Remove the "CVAC" directory
  ansible.builtin.file:
    path: /tmp/{{ item }}
    state: absent

