---
# This playbook sets up KVM on the hypervisor, in this case Rocky 8.7 was used.
- name: Install GlusterFS on Rocky Linux 
  hosts: hdd
  gather_facts: yes
  become: yes
  tasks:

    - name: Install Gluster fix.
      ansible.builtin.dnf:
        name: centos-release-gluster9
        state: latest

    - name: Install GLuster packages.
      ansible.builtin.dnf:
        name:
          - glusterfs
          - glusterfs-libs
          - glusterfs-server
        state: latest

    - name: Enable and start services
      ansible.builtin.systemd:
        name: "{{ item }}"
        state: started
        enabled: yes
      loop:
        - glusterfsd.service
        - glusterd.service

    - name: Enable glusterfs through the firewall
      ansible.posix.firewalld:
        service: glusterfs
        permanent: true
        state: enabled

    - name: reload service firewalld
      systemd:
        name: firewalld
        state: reloaded
      changed_when: no

    - name: Create a trusted storage pool
      gluster.gluster.gluster_peer:
        state: present
        nodes: "{{ ansible_play_hosts }}"
      run_once: true

    - name: Create the brick directory
      ansible.builtin.file:
        path: /data/volume1/brick1
        state: directory
        mode: '0755'

    # https://www.jeffgeerling.com/blog/simple-glusterfs-setup-ansible
    - name: create gluster volume
      gluster.gluster.gluster_volume:
        state: present
        name: gv1
        bricks: /data/volume1/brick1
        rebalance: yes
        cluster: "{{ ansible_play_hosts | join(',') }}"
        host: "{{ inventory_hostname }}"
      # with_inventory_hostnames: hdd
      run_once: true
