---
# tasks file for kvm_provision
- name: Deploy a KVM machine
  hosts: infra
  gather_facts: no
  become: yes
  tasks:
  
    - name: VM provision role
      ansible.builtin.include_role:
        name: kvm_provision


