---
- name: Configure Gluster on the HDD hosts
  hosts: hdd
  gather_facts: yes
  become: yes
  tasks:
  
    - name: Gluster provision role
      ansible.builtin.include_role:
        name: gluster
      
- name: Configure Gluster on the NVMe hosts
  hosts: nvme
  gather_facts: yes
  become: yes
  tasks:

    - name: Gluster provision role
      ansible.builtin.include_role:
        name: gluster
  


