---

- name: Install Gluster fix(es).
  ansible.builtin.dnf:
    # name: vdsm-gluster
    name: 
      - centos-release-gluster9
      - centos-release-ovirt45
    state: latest

- name: Install Gluster packages.
  ansible.builtin.dnf:
    name:
      - glusterfs
      - glusterfs-libs
      - glusterfs-server
      - vdsm-gluster
    state: latest

- name: Enable and start services
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: started
    enabled: yes
  loop:
    - glusterfsd.service
    - glusterd.service

- name: Enable glusterfs through the firewall
  ansible.posix.firewalld:
    service: glusterfs
    permanent: true
    state: enabled

- name: reload service firewalld
  systemd:
    name: firewalld
    state: reloaded
  changed_when: no

- name: Create a trusted storage pool
  gluster.gluster.gluster_peer:
    state: present
    nodes: "{{ ansible_play_hosts }}"
  run_once: true

- name: Create the brick directory
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop: "{{ gluster_brick_dir }}"

# https://www.jeffgeerling.com/blog/simple-glusterfs-setup-ansible
- name: create gluster volume
  gluster.gluster.gluster_volume:
    state: present
    name: "{{ gluster_brick_name }}"
    bricks: "{{ gluster_brick_dir | join(',') }}"
    rebalance: yes
    cluster: "{{ ansible_play_hosts | join(',') }}"
    host: "{{ inventory_hostname }}"
  run_once: true
